### ISSUE TITLE
Packages won't remove

### ISSUE THREAD

**Issue by dkfsalt** [saltstack/salt-winrepo-ng#1593]
This is probably best explained with an example.  

Test server is Windows 2016

```[root@sse600-04 salt-winrepo-ng]# salt sse600-04-windows1 pkg.list_pkgs
sse600-04-windows1:
    ----------
    Microsoft Visual C++ 2017 Redistributable (x64) - 14.12.25810:
        14.12.25810.0
    salt-minion:
        2019.2.0
[root@sse600-04 salt-winrepo-ng]# salt sse600-04-windows1 pkg.install wireshark
sse600-04-windows1:
    ----------
    Wireshark 2.6.6 64-bit:
        ----------
        new:
            2.6.6
        old:
    wireshark:
        ----------
        install status:
            success
[root@sse600-04 salt-winrepo-ng]# salt sse600-04-windows1 pkg.list_pkgs
sse600-04-windows1:
    ----------
    Microsoft Visual C++ 2017 Redistributable (x64) - 14.12.25810:
        14.12.25810.0
    Wireshark 2.6.6 64-bit:
        2.6.6
    salt-minion:
        2019.2.0
[root@sse600-04 salt-winrepo-ng]# salt sse600-04-windows1 pkg.remove wireshark
sse600-04-windows1:
    ----------
    wireshark:
        ----------
        current:
            not installed
[root@sse600-04 salt-winrepo-ng]# salt sse600-04-windows1 pkg.list_pkgs
sse600-04-windows1:
    ----------
    Microsoft Visual C++ 2017 Redistributable (x64) - 14.12.25810:
        14.12.25810.0
    Wireshark 2.6.6 64-bit:
        2.6.6
    salt-minion:
        2019.2.0
[root@sse600-04 salt-winrepo-ng]# salt sse600-04-windows1 grains.get cpuarch
sse600-04-windows1:
    AMD64
[root@sse600-04 salt-winrepo-ng]# salt --version
salt 2019.2.0-4967-gdcaf7d9 (Fluorine)

```

I've not done exhaustive testing, but I've found a few that fail this way (see below), there are likely others:
- golang
- git
- wireshark
- winrar

**Comment by dafyddj** [comment]
The issue, at least where Wireshark is concerned, is that Salt is not matching the install string ("Wireshark 2.6.6 64-bit") with what's specified in the package definition, so as far as Salt is concerned, Wireshark (the pkg) isn't installed.

`install status: success` just means that the install command returned a successful exit code.

The package definitions for these programs obviously need tidying up.

**Comment by dkfsalt** [comment]
Or maybe do a case insensitive search?

**Comment by dafyddj** [comment]
Feel free to open an issue on the main Salt repo, if that's the case.

**Comment by dkfsalt** [comment]
Looking for opinion.  Should we fix the repo defn's or modify the behavior of pkg?  I'm thinking the latter is better but I'm new to salt, so...

**Comment by UtahDave** [comment]
This looks like the repo package definition needs to be updated so it can find the installed software.

**Comment by dafyddj** [comment]
At least where Wireshark is concerned, it's not a question of case sensitivity but the full name string doesn't match and needs fixing.

**Comment by TerraTalpi** [comment]
I have investigated and hopefully fixed golang and wireshark.
**Wireshark: ** was using the .exe installer. They have changed the `fullname` from 2.0.0 to 2.6.x to 3.0.0 for the .exe installer, that's why it's difficult to distinguish it. The MSI-Installer starting with 2.4.0 always uses the `fullname` of "Wireshark". I have migrated the installation routine to the MSI installer except for 2.0.0 to 2.2.x, they are still the .exe installer.

I have tested installation and uninstallation of the packages, and all work. However, existing installations that have been done with .exe installers from 2.4.0 up to the latest version may not be recognized correctly. They have to be manually removed one time, but then after a salt installation you can just install, remove and upgrade the versions with salt.
