### ISSUE TITLE
salt-minion-py3.sls has wrong definitions for 3004

### ISSUE THREAD

**Issue by H20-17** [saltstack/salt-winrepo-ng#1916]
In the formula file salt-minion-py3.sls we see this:

```
salt-minion-py3:
  {%
      for version in [
          '3004-3',
          '3004-2',
          '3004',
          '3003.3',
          '3002.7',
          '3001.8',
      ]
  %}
 '{{ version }}':
```
However no matter whether we install from installer 3004-3, 3004-2, or 3004, in the registry the version always appears as 3004. That means that _{{ version }}_ will never match if we install from 3004-3 or 3004-2.

Should installers 3004-2 and 3004 really be referenced at all, since they are presumably supplanted by 3004-3 anyway?

**Comment by dafyddj** [comment]
`3004-3` **does** appear in the registry as `3004-3`; this was fixed by @twangboy.
It's a best practice in `winrepo` not to remove installer versions. Salt needs to know all the version numbers so that those can be uninstalled by Salt if necessary.
You're right, `3004-2` does break this pattern, but its installer is still available on `repo.saltproject.io`, and hasn't been pulled due to CVEs, so I guess it makes sense that someone should be able to install it if they so wished for whatever reason.

**Comment by H20-17** [comment]
Yes, this seems to be the cause. The other day I thought I thouight installed 3004-3 and and seen the version as 3004. Anyway I'll close this on the assumption that I was really tired and was just seeing things or messed up somehow.
