### ISSUE TITLE
Adobe Reader DC download links broken

### ISSUE THREAD

**Issue by grandmasterv** [saltstack/salt-winrepo-ng#352]
Hello!

It looks like the download locations for Adobe Reader DC have changed.

Old Broken Link
https://ardownload2.adobe.com/pub/adobe/reader/win/AcrobatDC/1501020059/AcroRdrDC1501020059_en_US.exe

New Working Link
https://admdownload.adobe.com/bin/live/readerdc_en_ha_install.exe

https://github.com/saltstack/salt-winrepo-ng/blob/master/adobereader-dc.sls

**Comment by hrumph** [comment]
@grandmasterv 
The link
https://ardownload2.adobe.com/pub/adobe/reader/win/AcrobatDC/1501020060/AcroRdrDC1501020060_en_US.exe

is working. It looks like adobe is purposefully making it's old links dead.

Note that when you use the new link the version of adobe reader dc you get
is 15.xxx.xxxxx
and NOT 2015.xxx.xxxx

This is because adobe has started a new versioning system and the 15.xxx.xxxx versions
are the "classic" track (as opposed to continuous track),

so we need to start fresh with a  new sls file called adobereader-dc-classic

It can start off with
```
  '15.010.20060':
    full_name: 'Adobe Acrobat Reader DC'
    installer: 'https://ardownload2.adobe.com/pub/adobe/reader/win/AcrobatDC/1501020060/AcroRdrDC1501020060_en_US.exe'
    install_flags: '/msi EULA_ACCEPT=YES ALLUSERS=1 REMOVE_PREVIOUS=YES /qn'
    uninstaller: 'msiexec.exe'
    uninstall_flags: '/qn /x {AC76BA86-7AD7-1033-7B44-AC0F074E4100} /norestart'
    msiexec: False
    locale: en_US
    reboot: False
```

**Comment by hrumph** [comment]
I'm closing this. It can be reopoenned if @grandmasterv is dissatisfied with the new merge.

**Comment by grandmasterv** [comment]
Looks good thanks!
