### ISSUE TITLE
firefox-esr.sls and firefox.sls consideration to simplify latest installer url

### ISSUE THREAD

**Issue by kevinrsalisbury** [saltstack/salt-winrepo-ng#873]
The existing .sls pair does work nicely for both versions of Firefox. However, if we are always looking for the latest installer revision, consider [this](https://ftp.mozilla.org/pub/firefox/releases/latest-esr/README.txt) and [this](https://ftp.mozilla.org/pub/firefox/releases/latest/README.txt) to download the latest every time without regular firefox-esr.sls and firefox.sls changes;

Latest Firefox ESR release (Win32): "https://download.mozilla.org/?product=firefox-esr-latest&os=win&lang=en-US"
Latest Standard Firefox release (Win32): "https://download.mozilla.org/?product=firefox-latest&os=win&lang=en-US"

For other operating systems replace 'os=win' with:
   Windows 64bit              os=win64
   OS X                       os=osx
   Linux x86_64               os=linux64
   Linux i686                 os=linux

I am using these urls with success with bash scripts to download the latest Firefox versions for multiple OSes, it seems like it may be easier to maintain inside an sls as well.

**Comment by TheBigBear** [comment]
@kevinrsalisbury hey kevin, sorry for not having responded to your helpful suggestion, so much appreciated.

This is great info, I have not tested it recently, but I believe the built-in salt winrepo downloader is way too dumb to 'cope' with this. ;-(
 
When I last tested this it absolutely needed to have a filename as lat part of the URL, or it would not recognise it as an executable. (it used to save it as whatever the last part of the URL was .... that dumb)

It would be great if you could test this for firefox, the next problem after that is solved would be to see how we can 'overcome' salt winrepo's need to know version numbers to know whether something is an upgrade or downgrade etc.

But I really like it otherwise as it would also allow us to address another pet hate of the current solution, and together with jinja code it would allow us to have one sls file to allow us to download whatever language version we require. With people being able to set a site or system default in a pillar and the sls would go off and download en_Gb or en_US or en_DE etc etc.
 
It would be really great and much appreciated if you could look into this a bit further and do some test of concept stuff on this?
